name: immuno_warriors
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.3
  share_plus: ^11.0.0
  screenshot: ^3.0.0
  network_info_plus: ^6.1.4
  bonsoir: ^5.1.11
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  intl: ^0.20.2
  vibration: ^3.1.3
  audioplayers: ^6.4.0
  flame: ^1.28.1
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  glassmorphism: ^3.0.0
  flutter_animate: ^4.5.2
  connectivity_plus: ^6.1.4
  flutter_neumorphic: ^3.2.0
  permission_handler: ^12.0.0+1
  wifi_iot: ^0.3.19+2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  hive: ^2.2.3
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  firebase_messaging: ^15.2.5
  cloud_functions: ^5.5.0
  path_provider: ^2.1.5
  logger: ^2.5.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  get_it: ^8.0.3
  uuid: ^4.5.1
  shimmer: ^3.0.0
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  go_router: ^15.1.2
  flutter_launcher_icons: ^0.14.3
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.4.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
  fonts:
    - family: MIXONE
      fonts:
        - asset: assets/fonts/MIXONE.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/animations/logo.png"