// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8FiNTnzsC0hxph0KhgYCUaVegOkLnP8',
    appId: '1:62703683654:web:e58e75caf7526e8992a247',
    messagingSenderId: '62703683654',
    projectId: 'immunowarriors-84410',
    authDomain: 'immunowarriors-84410.firebaseapp.com',
    storageBucket: 'immunowarriors-84410.firebasestorage.app',
    measurementId: 'G-M9ECYEJR14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfYu0dF9cIwWxW4NGplp6rtv0gfT056R8',
    appId: '1:62703683654:android:53152f74284fe95092a247',
    messagingSenderId: '62703683654',
    projectId: 'immunowarriors-84410',
    storageBucket: 'immunowarriors-84410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT960FI8bRZV-6-p9mzH2Rb6zOQrsjK0s',
    appId: '1:62703683654:ios:82cfd6944401041292a247',
    messagingSenderId: '62703683654',
    projectId: 'immunowarriors-84410',
    storageBucket: 'immunowarriors-84410.firebasestorage.app',
    iosBundleId: 'com.example.immunoWarriors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT960FI8bRZV-6-p9mzH2Rb6zOQrsjK0s',
    appId: '1:62703683654:ios:82cfd6944401041292a247',
    messagingSenderId: '62703683654',
    projectId: 'immunowarriors-84410',
    storageBucket: 'immunowarriors-84410.firebasestorage.app',
    iosBundleId: 'com.example.immunoWarriors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb8FiNTnzsC0hxph0KhgYCUaVegOkLnP8',
    appId: '1:62703683654:web:f6d778951031af9592a247',
    messagingSenderId: '62703683654',
    projectId: 'immunowarriors-84410',
    authDomain: 'immunowarriors-84410.firebaseapp.com',
    storageBucket: 'immunowarriors-84410.firebasestorage.app',
    measurementId: 'G-BPNZGSJ543',
  );
}
